server:
  port: 8081
  servlet:
    context-path: /auth

spring:
  application:
    name: uaaservice
  datasource:
    url: jdbc:mysql://mysql:3306/spring_security_uaa?useSSL=false
    username: root
    password: root1234
    driver-class-name: com.mysql.jdbc.Driver
  shardingsphere:
    sharding:
      default-database-strategy:
      tables:
  main:
    allow-bean-definition-overriding: true

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML
    encoding: UTF-8
  cloud:
    nacos:
      server-addr: nacos:8848
  mvc:
    static-path-pattern: /static/**


mybatis:
  type-aliases-package: com.example.uaa.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.example: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
pattern:
  name: 本地环境local

